# Generated by Django 3.2.4 on 2021-07-13 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_auto_20210713_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=200)),
                ('description', models.CharField(max_length=300)),
                ('photo', models.ImageField(upload_to='people/pictures')),
            ],
        ),
        migrations.DeleteModel(
            name='People',
        ),
    ]
